version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
    - echo Installing required packages
    - yum update -y
    - yum install -y unzip wget jq
    - echo Installing Terraform
    - cd /tmp
    - wget -q https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
    - unzip -q terraform_1.6.0_linux_amd64.zip
    - chmod +x terraform
    - mv terraform /usr/local/bin/
    - cd $CODEBUILD_SRC_DIR
    - terraform --version
    - echo Terraform installation complete

  pre_build:
    commands:
    - echo Pre-build phase started on `date`
    - echo Current directory is `pwd`
    - ls -la
    - echo "Creating backend configuration for CI/CD..."
    - cd terraform
    - |
      cat > backend-cicd.hcl << EOF
      bucket         = "dofs-terraform-state-4aa0782d"
      key            = "terraform.tfstate"
      region         = "ap-south-1"
      encrypt        = true
      dynamodb_table = "dofs-terraform-locks"
      EOF
    - echo "Backend configuration created:"
    - cat backend-cicd.hcl
    - echo "Initializing Terraform with backend config..."
    - terraform init -input=false -backend-config=backend-cicd.hcl

  build:
    commands:
    - echo Build started on `date`
    - echo "🚀 Running 3-Stage Deployment to Handle Circular Dependency"
    - echo "=================================================="
    - cd $CODEBUILD_SRC_DIR
    - chmod +x deploy-infrastructure.sh
    - export PROJECT_NAME=$PROJECT_NAME
    - export ENVIRONMENT=$ENVIRONMENT
    - export AWS_REGION=$AWS_DEFAULT_REGION
    - echo "Configuration:"
    - echo "  Project: $PROJECT_NAME"
    - echo "  Environment: $ENVIRONMENT"
    - echo "  Region: $AWS_REGION"
    - ./deploy-infrastructure.sh

  post_build:
    commands:
    - echo Build completed on `date`
    - echo "Deployment result:"
    - cd terraform
    - terraform output -json > terraform_outputs.json || echo "No outputs available"
    - echo "Terraform outputs:"
    - cat terraform_outputs.json || echo "No outputs to display"
    - echo "🎉 3-Stage Deployment Complete!"
    - echo "✅ Circular dependency resolved automatically"

artifacts:
  files:
  - terraform/terraform_outputs.json
  - terraform/**/*
  name: terraform-outputs

cache:
  paths:
  - '/root/.terraform/**/*'
  - 'lambdas/**/node_modules/**/*'
