version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
    - echo Installing dependencies

  pre_build:
    commands:
    - echo Pre-build phase started on `date`
    - echo Installing Lambda dependencies

  build:
    commands:
    - echo Build started on `date`
    - echo Building Lambda functions

    # Build API Handler
    - cd lambdas/api_handler
    - npm install --production
    - cd ../..

    # Build Validator
    - cd lambdas/validator
    - npm install --production || echo "No dependencies to install"
    - cd ../..

    # Build Order Storage
    - cd lambdas/order_storage
    - npm install --production
    - cd ../..

    # Build Fulfill Order
    - cd lambdas/fulfill_order
    - npm install --production
    - cd ../..

    - echo Lambda functions built successfully

  post_build:
    commands:
    - echo Build completed on `date`

artifacts:
  files:
  - '**/*'
  discard-paths: no

cache:
  paths:
  - lambdas/**/node_modules/**/*
